### ISSUE TITLE
module 'cv2.cv2' has no attribute 'DualTVL1OpticalFlow_create'

### ISSUE THREAD

**Issue by Light--** [tsenst/CrowdFlow#3]
hello, what's the requirement of running this project, i followed the README in ubuntu16.04 with opencv 4.1.1 but got error:

```python3 opticalflow_estimate.py /home/xxx/dataset/middlebury/test/ dual farneback plk ```

Traceback (most recent call last):
  File "opticalflow_estimate.py", line 118, in <module>
    main()
  File "opticalflow_estimate.py", line 116, in main
    run_parameter(config_item)
  File "opticalflow_estimate.py", line 39, in run_parameter
    dual_proc = cv2.DualTVL1OpticalFlow_create(config_item["parameter"]["tau"],
AttributeError: module 'cv2.cv2' has no attribute 'DualTVL1OpticalFlow_create'

**Comment by tsenst** [comment]
I have taken a look into the OpenCV 3.4.2 documentation:
https://docs.opencv.org/3.4.2/dc/d47/classcv_1_1DualTVL1OpticalFlow.html#a382eeb0d23bf9b91ecd2c4e07e1dacd1
and the creator function for the DualTVL1 is the same. Maybe somehow OpenCV has not been installed successfully with pip. Can check with `pip list` or `pip3 list` if OpenCV is available for Python3?

**Comment by Light--** [comment]
FYI.

 ```
$ pip3 list
Package               Version
--------------------- --------
numpy                 1.17.2
opencv-contrib-python 4.1.1.26
pip                   19.2.3
pkg-resources         0.0.0
progressbar2          3.46.1
python-utils          2.3.0
setuptools            41.2.0
six                   1.12.0
wheel                 0.33.6

```

**Comment by Light--** [comment]
> I have taken a look into the OpenCV 3.4.2 documentation:
> https://docs.opencv.org/3.4.2/dc/d47/classcv_1_1DualTVL1OpticalFlow.html#a382eeb0d23bf9b91ecd2c4e07e1dacd1
> and the creator function for the DualTVL1 is the same. Maybe somehow OpenCV has not been installed successfully with pip. Can check with `pip list` or `pip3 list` if OpenCV is available for Python3?

FYI. sorry, the version of the opencv used in env is 4.1.1, out of the env is 3.4.2, i made a mistake. The error happens when i ran the code in env.

 ```
$ pip3 list
Package               Version
--------------------- --------
numpy                 1.17.2
opencv-contrib-python 4.1.1.26
pip                   19.2.3
pkg-resources         0.0.0
progressbar2          3.46.1
python-utils          2.3.0
setuptools            41.2.0
six                   1.12.0
wheel                 0.33.6

```
When i change to use opencv 3.4.2, it worked.
